name: Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 boto3 lxml flake8

      - name: Lint scraper
        run: flake8 scraper/scraper.py --max-line-length=120

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.9

      - name: Terraform validate
        run: |
          cd terraform
          terraform init -backend=false
          terraform validate

      - name: Check project structure
        run: |
          test -f scraper/scraper.py
          test -f glue-job/books_etl_job.py
          test -f docs/athena_queries.sql
          test -f docker/docker-compose.yml
          echo "All files present"
